<?php
// Generated by Zend Framework 2
return array(
    'XelaxPasswordGeneratorModule\Module'                       => __DIR__ . '/Module.php',
    'XelaxPasswordGeneratorModule\Options\GeneratorOptions'     => __DIR__ . '/src/XelaxPasswordGeneratorModule/Options/GeneratorOptions.php',
    'XelaxPasswordGeneratorModule\PluginManager\PluginManager'  => __DIR__ . '/src/XelaxPasswordGeneratorModule/PluginManager/PluginManager.php',
    'XelaxPasswordGeneratorModule\Service\PluginManagerFactory' => __DIR__ . '/src/XelaxPasswordGeneratorModule/Service/PluginManagerFactory.php',
);